site_name: Generative GameDev
site_url: http://localhost.com:8000/
repo_url: https://github.com/stefanwebb/generative-gamedev
repo_name: generative-gamedev
use_directory_urls: true

theme:
  name: material
  custom_dir: overrides
  user_color_mode_toggle: true
  locale: en
  logo: img/vlog-logo.svg
  font:
    text: Quicksand
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: fontawesome/solid/link
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: purple
      primary: purple
      # accent: purple
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      # accent: black
      toggle:
        icon: fontawesome/solid/moon
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - navigation.sections
    - navigation.path
  icon:
    favicon: images/favicon.svg
    repo: fontawesome/solid/code
    search: fontawesome/solid/magnifying-glass

extra_css:
  - stylesheets/extra.css

nav:
  - About: about.md
  - Vlog:
    - index.md
  - References: references.md

plugins:
  - search
  - blog:
      post_url_format: "{slug}"
      archive: true
      draft_on_serve: false
      blog_dir: .

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

hooks:
  - hooks/socialmedia.py

extra:
  social:
    - icon: fontawesome/brands/mastodon
      name: squidfunk on Mastodon
      link: https://fosstodon.org/@squidfunk